// Listen for messages from content script or popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (request.action === 'analyzeContent') {
        analyzeContent(request.content)
            .then(result => sendResponse({ success: true, result }))
            .catch(error => sendResponse({ success: false, error: error.message }));
        return true;
    }
});

async function analyzeContent(content) {
    // TODO: Implement LLM API integration
    // This is a placeholder for the actual API call
    return {
        biasAnalysis: 'Bias analysis will be implemented with LLM API',
        factCheck: 'Fact checking will be implemented with LLM API',
        summary: 'Summary will be generated by LLM API'
    };
}

// Handle extension installation
chrome.runtime.onInstalled.addListener(() => {
    console.log('BiasLens extension installed');
}); 