document.addEventListener('DOMContentLoaded', function() {
    const analyzeBtn = document.getElementById('analyze-btn');
    const loadingDiv = document.getElementById('loading');
    const resultsDiv = document.getElementById('results');
    const errorDiv = document.getElementById('error');

    analyzeBtn.addEventListener('click', async function() {
        // Show loading state
        loadingDiv.classList.remove('hidden');
        resultsDiv.classList.add('hidden');
        errorDiv.classList.add('hidden');

        try {
            // Get the active tab
            const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
            
            // Send message to content script to extract article content
            const response = await chrome.tabs.sendMessage(tab.id, { action: 'extractContent' });
            
            if (response && response.content) {
                // TODO: Send content to LLM API for analysis
                // For now, we'll just display the extracted content
                document.getElementById('bias-analysis').textContent = 'Bias analysis will be implemented with LLM API';
                document.getElementById('fact-check').textContent = 'Fact checking will be implemented with LLM API';
                document.getElementById('summary').textContent = 'Summary will be generated by LLM API';
                
                // Show results
                loadingDiv.classList.add('hidden');
                resultsDiv.classList.remove('hidden');
            } else {
                throw new Error('No content extracted');
            }
        } catch (error) {
            console.error('Error:', error);
            loadingDiv.classList.add('hidden');
            errorDiv.classList.remove('hidden');
        }
    });
}); 